# Generated by Django 4.1.6 on 2023-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='options',
            new_name='option',
        ),
    ]
